Enable basic PHPSTAN checks
mautic/api-library pull request #239
Opened 2021-02-24 19:40 UTC by dennisameling

Sets up basic PHPSTAN checks. Setting the level higher than 1 causes quite some errors/warnings, so I'm leaving it at 1 for now.

2021-02-25 20:02 UTC, RCheesley commented
@dennisameling do you need me to test this or is it just a case of getting the green tick to merge? 🤓 ✅

2021-02-27 10:32 UTC, escopecz requested changes
Found 1 line that doesn't/didn't make sense and suggested change. Let me know if it make sense. Otherwise this is good to go 👍

2021-02-27 10:32 UTC, escopecz commented on tests/Api/CampaignsTest.php
> +                $this->assertFalse(var_export($event, true), 'Event ID not recognized in the log.');
This doesn't make much sense. The previous version did not make sense either. I expect the intent was to fail the test if this assert will run. How about this:
```suggestion
                $this->fail('Event ID not recognized in the log.'.var_export($event, true));
```

2022-01-04 16:16 UTC, escopecz commented on tests/Api/CampaignsTest.php
> +                $this->assertFalse(var_export($event, true), 'Event ID not recognized in the log.');
@dennisameling WDYT?

2023-05-02 14:38 UTC, RCheesley commented
@escopecz some conflicts with this PR - suggest that we have someone from @mautic/core-team pick this up if we want to merge it?

2024-07-18 15:07 UTC, closed without merging